### ISSUE TITLE
Too much bloat

### ISSUE THREAD

**Issue by uglycoyote** [keokilee/react-typescript-boilerplate#186] opened 2016-03-28 05:50 UTC
167 Megabytes for a boilerplate?  
With all of the dependencies here, this boilerplate generated paths so long that windows was not even able to delete the files!
Need to google search just to figure out how to delete this thing now!

**Comment by dziamid** [comment] 2016-11-10 09:53
@uglycoyote  Use yarn package manager, it flattens dependencies, so long paths should not be a problem

**Comment by keokilee** [comment] 2016-11-24 18:00
Closing this because I'm not sure what the issue is. I get that there are a lot of deps and 167 MB is a lot, but I think that a boilerplate by definition has everything you need to get started. It'd probably be more productive to discuss what should be removed and if that would fix any issues.

**Closed as completed by keokilee** 2016-11-24 18:00 UTC

**Comment by uglycoyote** [comment] 2016-11-24 21:58
Yes, sorry.  I come to slightly accept that boilerplates in the web world are commonly a large fraction of a gigabyte.  I believe newer versions of npm have done something to get around the ultra-deep directory trees caused by dependencies of dependencies of dependencies.  My frustration was really with this and the fact that Windows was unable to delete the directory because it was too deep, which is more of a npm/windows issue than a issue with your project.

So sorry to single your boilerplate project out when it is just one in a sea of bulging bulbous boilerplates, and thanks for putting it out there to begin with.
